### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by straybro** [oldbk/db#1]

**Comment by oldbk** [comment]
> _No description provided._

самой собой, все таблицы

**Comment by straybro** [comment]
Я может втыканул, и где то в других репах есть чет подобное, но именно в этой репе вижу только чистую схему и дамп форума в архиве. Я о словарных таблицах, типа quests, shops, magics. Потом я глянул что там 400＋таблиц в схеме и судя по многомиллионных автоинкрементах в таблицах, дамп бы занимал несколько десятков Гб и понял, что врядли это сливалось.

**Comment by oldbk** [comment]
> Я может втыканул, и где то в других репах есть чет подобное, но именно в этой репе вижу только чистую схему и дамп форума в архиве. Я о словарных таблицах, типа quests, shops, magics. Потом я глянул что там 400＋таблиц в схеме и судя по многомиллионных автоинкрементах в таблицах, дамп бы занимал несколько десятков Гб и понял, что врядли это сливалось.

В @oldbk_shop сейчас как раз новогодние распродажи: заточки +10, арты, доспехи, таблицы БД разных лет 💯
